Lab 1
AnatoliiYarovyi/WebAPICoffeeShop pull request #2
Opened 2024-09-18 16:34 UTC by AnatoliiYarovyi

Добрий вечір,

я додав в "Program.cs" цей рядок так як без нього не працювало
`builder.Services.AddSingleton<CoffeeShopContext>();`

Намагався змінити назву папок але так теж не працює тому їх не змінював
![image](https://github.com/user-attachments/assets/c905faf8-cc8e-494a-ab0e-86fc99556f47)

2024-09-18 18:58 UTC, NataliiaRastoropova requested changes
Щоб не було проблем з перейменуванням проєкт потрібно створювати з нуля, (а мій проєкт використовувати як приклад). Також я не бачу тут реалізації трьохрівневої архітектури (необхідно використати приклад  гілки master).

2024-09-18 19:00 UTC, AnatoliiYarovyi commented
Зрозумів, дякую!

2024-09-22 18:01 UTC, NataliiaRastoropova commented on CoffeeShopAPI.DataAccess/CoffeeShopContext.cs
> +                    OrderDate = DateTime.Now
It's better to use Date.Time.UtcNow

2024-09-22 18:01 UTC, NataliiaRastoropova commented on CoffeeShopAPI.BusinessLogic/Class1.cs
> +﻿namespace CoffeeShopAPI.BusinessLogic
Please, remove unused class

2024-09-22 18:01 UTC, NataliiaRastoropova commented on CoffeeShopAPI.DataAccess/Class1.cs
> +﻿namespace CoffeeShopAPI.DataAccess
Please, remove unused class

2024-09-22 18:03 UTC, NataliiaRastoropova commented on CoffeeShopAPI.Infrastructure/Class1.cs
> +﻿namespace CoffeeShopAPI.Infrastructure
Please, remove unused class

2024-09-22 18:36 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Models/Coffee/CreateAccountRequest.cs
> +public class CreateCoffeeRequest
Please rename your file based on your class name

2024-09-22 18:38 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +            _logger.LogError(e, $"Failed to fetch accounts");
Error massage is not informative

2024-09-22 18:39 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +    public async Task<ActionResult<IEnumerable<CoffeeDto>>> GetAccount()
Rename, like GetCoffeeList

2024-09-22 18:40 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +    public async Task<ActionResult<CoffeeDto>> GetAccountById([FromRoute] string id)
Rename please like GetCoffeeById

2024-09-22 18:40 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +            _logger.LogError(e, $"Failed to fetch accounts");
same for log message

2024-09-22 18:41 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +            _logger.LogError(ex, $"Failed to update account with id={entity.Id}");
uninformative log message

2024-09-22 18:42 UTC, NataliiaRastoropova commented on CoffeeShopAPI/Controllers/CoffeeController.cs
> +            _logger.LogInformation($"Account {entity.Id} successfully updated");
uninformative log message

2024-09-22 18:43 UTC, AnatoliiYarovyi commented
@NataliiaRastoropova, 
Hello!

This is not the final version,
So far I've tried to make a minimal working app

I will remove unused code
Thanks for your comments!!!

2024-09-22 18:44 UTC, NataliiaRastoropova commented on CoffeeShopAPI.BusinessLogic/Installers/CoffeeInstaller.cs
> +    public static IServiceCollection AddCoffee(this IServiceCollection services)
Name is not informative

2024-09-22 18:46 UTC, NataliiaRastoropova requested changes
Please fix miner issues with naming, log error messages, file naming

2024-09-25 15:18 UTC, AnatoliiYarovyi commented
@NataliiaRastoropova , hello!
Added changes:
 - [removed unused classes](https://github.com/AnatoliiYarovyi/WebAPICoffeeShop/pull/2/commits/a94708cd9a240404cf520bcf0480096427a08dbc)
 - [renamed files and entities from coffee to products](https://github.com/AnatoliiYarovyi/WebAPICoffeeShop/pull/2/commits/540b631b9d67c95e6bdebd0f149fae09ef013f06)
 because I decided that working with products would be more efficient and more convenient

2024-09-25 16:46 UTC, NataliiaRastoropova approved these changes
Looks good for me!

2024-09-25 16:50 UTC, NataliiaRastoropova commented
Please merge pull request as regular merge or squash
<img width="517" alt="Screenshot 2024-09-25 at 19 49 38" src="https://github.com/user-attachments/assets/8d7af8b9-0fb1-4fb9-aa24-487bdd12789c">

2024-09-25 17:30 UTC, merged